module.exports = {
  rep : ['seven deadly sins','91days','ajin','akame ga kill','amd','among us','anastasia','android','angelbeats','angular','another','apple','assassination classroom','assassins pride', "assassin's creed origins","atlantide l'empire perdu",'arrete-moi si tu peux','audacity','baki','banana fish','beat saber','black mirror','boku no pico','boneworks','brave','breaking bad','b the begining','btooom','bungou stray dogs','civilization iv','cluster truck','code geass','counter strike global offensive','cuphead','cyberpunk','darksouls','dead cells','dead man wonderland','deathnote','demon slayer','demon slayer','discord','dr stone','edge of tomorrow','elfen lied','epic games','erased','euphoria','evengelion','fire force','fl studio','full metal alchemist','frostpunk','gambling school','game of thrones','the god of highschool','god of war','gog','google','google chrome','gravity falls','gundam','haikyuu','halflife','hardcore henri','harry potter',"hellblade Senua's sacrifice",'inception','ironman 2','javascript','john wick','jojo','jumanji','just cause 3','kaguya sama','kingsman','konosuba','kyoukai no kanata','law breakers','le loup de walstreet','league of legends','love death and robots','made in abyss','men in black','my hero academia','minecraft','mirai nikki','mob psycho 100','mortel','mr robot','narcos','nier automata','nodejs','no game no life','no guns life',"no man's sky",'nvidia','old boy','one piece','one piece','oneshoot','ocarina of time','one punch time','overlord','owerwatch','owari no seraph','payday 2','persona 5','photoshop','portal 2','the promised neverland','pulpfiction','python','rainbow six','ratatouille','razer','react','ready player one','red dead redemption 2','re zero','rick et morty','samurai champloo','sword art online','sekiro','seul sur mars','sex education',"l'attaque des titans",'solo leveling','spiderman','the stanley parable','star cityzen','steam','steins gate','super hot','super mario galaxy 2','super meat boy','switch','teamspeak','the boys','the mask','the witcher','tokyoghoul','toy story','trigun','undertale','unrealengine','visual studio code','yakuza','your lie in april','yourname'],//liste de réponses associés aux images.


  repalias : ['7 deadly sins','91 days','ajin','akame ga kill','amd','among us','anastasia','android','angelbeats','angular','another','apple','assassination classroom','assassins pride', "assassin's creed origins","atlantide",'arrete moi si tu peux','audacity','baki','banana fish','beat saber','black mirror','boku no pico','boneworks','brave','breaking bad','b the begining','btooom','bungou stray dogs','civilization iv','cluster truck','code geass','counter strike global offensive','cuphead','cyberpunk','darksouls 2','dead cells','dead man wonderland','deathnote','demon slayer','demon slayer','discord','dr stone','edge of tomorrow','elfen lied','epic games','erased','euphoria','evengelion','fire force','fruity loop studio','full metal alchemist','frostpunk','gambling school','game of thrones','the god of highschool','god of war','gog','google','google chrome','gravity falls','gundam','haikyuu','halflife','hardcore henri','harry potter',"hellblade Senua's sacrifice",'inception','ironman 2','javascript','john wick',"jojo's bizarre adventure",'jumanji','just cause 3','kaguya sama','kingsman','Kono subarashii sekai ni shukufuku o','kyoukai no kanata','law breakers','le loup de walstreet','league of legends','love death and robots','made in abyss','men in black','my hero academia','minecraft','mirai nikki','mob psycho 100','mortel','mr robot','narcos','nier automata','nodejs','no game no life','no guns life',"no man's sky",'nvidia','old boy','one piece','one piece','oneshoot','the legend of zelda ocarina of time','one punch time','overlord','owerwatch','owari no seraph','payday 2','persona 5','photoshop','portal 2','promised neverland','pulpfiction','python','rainbow six','ratatouille','razer','react','ready player one','red dead redemption 2','re zero','rick et morty','samurai champloo','sword art online','sekiro','seul sur mars','sex education',"shingeki no kyojin",'solo leveling','spiderman','stanley parable','star cityzen','steam','steins gate','super hot','super mario galaxy 2','super meat boy','switch','teamspeak','the boys','the mask','the witcher','tokyoghoul','toy story','trigun','undertale','unrealengine','visual studio code','yakuza','your lie in april','kimi no na wa'],//aliases pour les réponses


  repalias2:['seven deadly sins','91 days','ajin','akame ga kill','amd','among us','anastasia','android','angelbeats','angular','another','apple','assassination classroom','assassins pride', "assassin's creed origins","atlantide l'empire perdu",'arrete-moi si tu peux','audacity','baki','banana fish','beat saber','black mirror','boku no pico','boneworks','brave','breaking bad','b the begining','btooom','bungou stray dogs','civilization iv','cluster truck','code geass','counter strike global offensive','cuphead','cyberpunk','darksouls 3','dead cells','dead man wonderland','deathnote','demon slayer','demon slayer','discord','dr stone','edge of tomorrow','elfen lied','epic games','erased','euphoria','evengelion','fireforce','fruity loop','full metal alchemist','frostpunk','gambling school','game of thrones','god of highschool','god of war','gog.com','google','google chrome','gravity falls','gundam','haikyuu','halflife 2','hardcore henri','harry potter',"hellblade Senua's sacrifice",'inception','ironman 2','javascript','john wick','jojo','jumanji','just cause 3','kaguya sama','kingsman','konosuba','kyoukai no kanata','law breakers','le loup de walstreet','league of legends','love death and robots','made in abyss','men in black','my hero academia','minecraft','mirai nikki','mob psycho 100','mortel','mr robot','narcos','nier automata','nodejs','no game no life','no guns life',"no man's sky",'nvidia','old boy','one piece','one piece','oneshoot','ocarina of time','one punch time','overlord','owerwatch','owari no seraph','payday 2','persona 5','photoshop','portal 2','the promised neverland','pulpfiction','python','rainbow six','ratatouille','razer','react','ready player one','red dead redemption 2','re zero','rick et morty','samurai champloo','sword art online','sekiro','seul sur mars','sex education',"attack on titan",'solo leveling','spiderman','the stanley parable','star cityzen','steam','steins gate','super hot','super mario galaxy 2','super meat boy','switch','teamspeak','the boys','the mask','the witcher','tokyoghoul','toy story','trigun','undertale','unrealengine','visual studio code','yakuza','your lie in april','yourname'],//aliases pour les réponses


  imgname : ['7deadlysince', '91days', 'ajin', 'akame_ga_kill', 'amd', 'among_us', 'anastasia', 'android', 'angelbeats', 'angular', 'another', 'apple', 'assassinationclassroom', 'assassins_pride', 'Assassin_s_Creed_Origins', 'atlantidelempireperdu', 'arretemoisitupeux', 'audacity', 'baki', 'banana_fish', 'beatsaber', 'blackmirror', 'bokunopico', 'boneworks', 'brave', 'breakingbad', 'bthebegining', 'btooom', 'bungoustraydogs', 'civ6', 'cluster_truck', 'codegeass', 'csgo', 'cuphead', 'cyberpunk', 'darksouls3', 'deadcells', 'deadmanwonderland', 'deathnote', 'demonslayer', 'demonslayer2', 'discord', 'drstone', 'edgeoftomorrow', 'elfenlied', 'epicgames', 'erased', 'euphoria', 'evengelion', 'fireforce', 'flstudio', 'fma', 'frostpunk', 'gamblingschool', 'gameofthrones', 'godofhighschool', 'godofwar', 'gog', 'google', 'googlechrome', 'gravityfalls', 'gundam', 'Haikyuu', 'halflife', 'hardcorehenri', 'harrypotter', "hellblade senua's sacrifice", 'inception', 'ironman2', 'javascript', 'johnwick', 'jojo', 'jumanji', 'just_cause_3', 'kaguya_sama', 'kingsman', 'konosuba', 'kyoukai_no_kanata', 'law_breakers', 'leloupdewalstreet', 'lol', 'lovedeathandrobots', 'madeinabyss', 'meninblack', 'mha', 'minecraft', 'mirainikki', 'mob_psycho_100', 'mortel', 'mrrobot', 'narcos', 'nier_automata', 'nodejs', 'nogamenolife', 'nogunslife', 'nomanssky', 'nvidia', 'oldboy', 'onepiece', 'onepiece2', 'oneshoot', 'oot', 'opm', 'overlord1', 'ow', 'owarinoseraph', 'payday2', 'persona_5', 'photoshop', 'portal2', 'promisedneverland', 'pulpfiction', 'python', 'rainbowsix', 'ratatouille', 'razer', 'react', 'readyplayerone', 'reddead2', 'rezero', 'rick_et_morty', 'samuraichamploo', 'sao', 'sekiro', 'seulsurmars', 'sexeducation', 'snk', 'sololeveling', 'spiderman', 'stanleyparable', 'starcityzen', 'steam', 'steinsgate', 'superhot', 'supermariogalaxy2', 'super_meat_boy', 'switch', 'teamspeak', 'theboys', 'themask', 'the_witcher', 'tokyoghoul', 'toystory', 'trigun', 'undertale', 'unrealengine', 'visualstudiocode', 'yakuza', 'yourlieinapril', 'yourname'], //nom des images stockés dans les fichiers locaux du bot.

  cquotes:['tu peux commencer aveugle et finir peintre',"Et le coupable, c'est vous!","De Québec City jusqu'à Djezaïr\nSuki na Koto dake oshiete tai",'Objection !'],

  cqrep:['nepal','professeur layton','nepal','phoenix wright'],
  
  cqrepalias:['klm','hershel layton','klm',],

  quotes:['The cake is a lie.','It’s dangerous to go alone ! Take This !','N’oubliez pas… pas de russe.'],

  qrep:['portal','the legend of zelda','call of duty modern warfare 2'],

  qrepalias:['portal','the legend of zelda','modern warfare 2'],

}